export enum PriceId {
  NEWS_LETTER = 'somme_price_id_1',
  PROFESSIONAL = 'somme_price_id_2',
  PREMIUM = 'somme_price_id_3',
  WEEKLY_SOCIAL_MEDIA_REPORTS_MONTHLY = 'somme_price_id_4_monthly',
  WEEKLY_SOCIAL_MEDIA_REPORTS_YEARLY = 'somme_price_id_4_yearly',
  LISTING_UPDATE_SERVICE_MONTHLY = 'somme_price_id_5_monthly',
  LISTING_UPDATE_SERVICE_YEARLY = 'somme_price_id_5_yearly',
  CONTACTS_501_2500_MONTHLY = 'somme_price_id_6_monthly',
  CONTACTS_501_2500_YEARLY = 'somme_price_id_6_yearly',
  CONTACTS_2501_5000_MONTHLY = 'somme_price_id_7_monthly',
  CONTACTS_2501_5000_YEARLY = 'somme_price_id_7_yearly',
  CONTACTS_5001_10000_MONTHLY = 'somme_price_id_8_monthly',
  CONTACTS_5001_10000_YEARLY = 'somme_price_id_8_yearly',
}
