export enum PriceId {
  ESSENTIAL_MONTHLY = 'price_1RlyO0EGvHQ5JsokKAF5kQfG',
  ESSENTIAL_YEARLY = 'price_1RlxEXEGvHQ5JsokyQ5zzq1i',
  PROFESSIONAL_MONTHLY = 'price_1RlxCrEGvHQ5JsokDrqm4gli',
  PROFESSIONAL_YEARLY = 'price_1RlxEvEGvHQ5JsokNustxOBi',
  PREMIUM_MONTHLY = 'price_1RlxDOEGvHQ5Jsokgm0TWprA',
  PREMIUM_YEARLY = 'price_1RlxFLEGvHQ5JsokHmEIKEIy',
  WEEKLY_SOCIAL_MEDIA_REPORTS_MONTHLY = 'price_1RlxFsEGvHQ5JsokzAiMQlBf',
  WEEKLY_SOCIAL_MEDIA_REPORTS_YEARLY = 'price_1RlxGOEGvHQ5JsokSQImjdTm',
  LISTING_UPDATE_SERVICE_MONTHLY = 'price_1RlxGqEGvHQ5JsokHINUlZI5',
  LISTING_UPDATE_SERVICE_YEARLY = 'price_1RlxHFEGvHQ5JsokKbNmPkpk',
  CONTACTS_501_2500_MONTHLY = 'price_1R08EGEGvHQ5JsokTBWYdxsP',
  CONTACTS_501_2500_YEARLY = 'price_1RlxA6EGvHQ5JsokirCXzI40',
  CONTACTS_2501_5000_MONTHLY = 'price_1R08F0EGvHQ5Jsok46cle2Dt',
  CONTACTS_2501_5000_YEARLY = 'price_1RlxAcEGvHQ5JsokzdbCrEmY',
  CONTACTS_5001_10000_MONTHLY = 'price_1R08FMEGvHQ5Jsokkm5gjfDz',
  CONTACTS_5001_10000_YEARLY = 'price_1RlxB4EGvHQ5JsoktajRuUId',
  DISCOUNT = '10percent_discount'
}
